meta:
  url: https://marcusnotheis.github.io/ui5-webcomponents-react-intro/
  title: UI5 Web Components for React Introduction
  description: A brief overview of using UI5 Web Components in React and how to improve developer experience using UI5 Web Components for React.
  siteName: UI5 Web Components for React
  sns: ["twitter"]
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: progressbar # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    languages:
      - javascript
      - html
      - jsx
    plugins:
      - line-numbers
    theme: okaida
