meta:
  url:
  title:
  description:
  siteName:
  sns: ["twitter"]
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    languages:
      - javascript
      - html
      - jsx
    plugins:
      - line-numbers
    theme: tomorrow
